Task 2
KulakovaEA/maths_prac pull request #3
Opened 2019-10-13 12:41 UTC by KulakovaEA

Have problems with access to the site with data so I can not check my k-means code. Other 5 problems are solved.

2019-10-13 13:01 UTC, illarionovEA commented
файл по ссылке https://www.stat.cmu.edu/~larry/all-of-statistics/=data/faithful.dat доступен
есть копия файла, например, здесь https://www.kaggle.com/janithwanni/old-faithful

2019-10-13 13:01 UTC, illarionovEA requested changes
нужно доделать k-means

2019-10-13 16:03 UTC, KulakovaEA commented
добавила k-means

2019-10-14 16:25 UTC, illarionovEA approved these changes

2019-10-15 18:48 UTC, merged