Task 6
KulakovaEA/maths_prac pull request #7
Opened 2019-11-24 15:29 UTC by KulakovaEA

Added homework 6.

2019-11-26 18:04 UTC, illarionovEA requested changes
замечание по сути: для предложенной схемы равномерное распределение не является стационарным. Стационарным будет распределение, для когорого вес графа пропорционален числу закрашенных вершиг.

замечение по коду:
```pyhton
def amount_of_black_ver(a, size):
    s = 0
    for i in range(size):
        for j in range(size):
            if (a[i,j] == True):
                s += 1
    return s
```
на самом деле эквивалентно просто np.sum(a)

2019-12-07 20:03 UTC, illarionovEA commented
Оценка получается завышенной. Значит алгоритм сходится не туда. Нужно внимательно проверять. В лекции есть ссылки на литературу, в них разобрана эта задача

2019-12-08 19:32 UTC, KulakovaEA commented
исправила

2019-12-14 13:35 UTC, illarionovEA commented
что-то не так в реализации. ожидается ответ около 15.

2019-12-18 22:48 UTC, KulakovaEA commented
Теперь вроде все хорошо

2019-12-19 20:38 UTC, illarionovEA approved these changes

2019-12-21 13:55 UTC, merged